mb fix?

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -78,6 +78,8 @@ jobs:
         if: failure()
         run: |
           set +e
+          set -eo pipefail
+          export CI_JOB_ID=1
           cat <<'EOF' > parse_testcases.sh
           #!/bin/bash
           TXT_FILE="junit/*.xml"
@@ -133,7 +135,7 @@ jobs:
 
           chmod +x parse_testcases.sh
           ./parse_testcases.sh > failure-report.txt
-          export FAILURE_REPORT=$(<failure-report.txt)
+          echo "::set-env name=FAILURE_REPORT::$(<failure-report.txt)"
       - name: Notify Telegram on failure
         if: failure()
         uses: appleboy/telegram-action@master
@@ -144,7 +146,7 @@ jobs:
           message: |
             *Commit did not pass test(s) ⚠️.*
             ```
-            ${{ FAILURE_REPORT }}
+            ${{ env.FAILURE_REPORT }}
             ```
       - name: Notify Telegram on success
         if: success()
